/** Shared helpers for displaying uploaded file URLs in the UI. */

export type FileKind = "image" | "audio" | "video" | "pdf" | "archive" | "other";

const IMAGE_EXT = new Set(["jpg", "jpeg", "png", "gif", "webp"]);
const AUDIO_EXT = new Set(["mp3", "mpeg", "ogg", "oga", "wav", "m4a", "aac"]);
const VIDEO_EXT = new Set(["mp4", "mov", "avi", "mkv", "mpeg", "flv", "3gp"]);
const ARCHIVE_EXT = new Set(["zip", "rar", "7z", "tar", "gz"]);

export function filenameFromUrl(url: string): string {
  try {
    const path = url.split("?")[0] ?? url;
    const part = path.split("/").pop();
    return part ? decodeURIComponent(part) : url;
  } catch {
    return url;
  }
}

export function getExtension(urlOrName: string): string {
  try {
    const clean = urlOrName.split("?")[0] ?? urlOrName;
    const base = clean.split("/").pop() ?? clean;
    const parts = base.split(".");
    return parts.length > 1 ? (parts.pop() || "").toLowerCase() : "";
  } catch {
    return "";
  }
}

/**
 * Strip storage prefixes (timestamps, UUIDs) so users see something readable.
 * e.g. `1790476903742-63c11e30-16c9-….jpeg` → short residual name, or empty if only ids.
 */
export function prettyFilename(name: string): string {
  let result = name.trim();
  if (!result) return "";

  // Leading numeric timestamp: 1790476897032-
  result = result.replace(/^\d{10,}-/, "");
  // UUID segment: 63c11e30-16c9-40c5-aee6-0dfecd99eb55
  result = result.replace(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}-?/i, "");
  // Autogenerated voice prefixes
  result = result.replace(/^voice-?(note)?-?\d*-?/i, "");
  // Another leading long digit run after the above
  result = result.replace(/^\d{8,}-/, "");

  result = result.replace(/^-+/, "").trim();

  // If nothing meaningful left besides extension, return empty (caller uses friendly label)
  const ext = getExtension(result);
  const stem = ext ? result.slice(0, -(ext.length + 1)) : result;
  if (!stem || /^[0-9a-f-]{8,}$/i.test(stem)) {
    return ext ? `.${ext}` : "";
  }

  if (result.length > 48) {
    const keepExt = ext ? `.${ext}` : "";
    const maxStem = 40 - keepExt.length;
    return `${stem.slice(0, Math.max(8, maxStem))}…${keepExt}`;
  }

  return result;
}

export function detectFileKind(url: string): FileKind {
  const ext = getExtension(url);
  const lower = url.toLowerCase();

  if (IMAGE_EXT.has(ext)) return "image";
  if (AUDIO_EXT.has(ext) || /voice[^/]*\.(webm|mp4|m4a)$/i.test(lower)) return "audio";
  if (ext === "webm") {
    // Non-voice webm → video; voice already handled above
    return "video";
  }
  if (VIDEO_EXT.has(ext)) return "video";
  if (ext === "pdf") return "pdf";
  if (ARCHIVE_EXT.has(ext)) return "archive";
  return "other";
}

/** Prefer attribute type when classifying media answers. */
export function resolveFileKind(url: string, attributeType?: "file" | "voice" | string): FileKind {
  if (attributeType === "voice") return "audio";
  const kind = detectFileKind(url);
  if (attributeType === "file" && kind === "audio" && getExtension(url) === "mp4") {
    return "video";
  }
  return kind;
}
